### ISSUE TITLE
シリアル端子からのコマンド送信機能が動かない

### ISSUE THREAD

**Issue by oknw3** [htlabnet/16_Segment_9_Digit_Display_Controller_For_v2#7]
V1コントローラ互換のシリアルからコマンドを送信する機能が動作していない。

**Comment by totegamma** [comment]
ワロタ。これはおそらくCPUが割り込みに忙しくなりすぎてメインのタスクに手が回ってないのが原因ですね....

**Comment by pcjpnet** [comment]
そもそも、PIC18で厳しいのであれば、次は PIC32MX795F512LT あたりを使うとか。ピンIOは多いので、シフトレジスタは不要になるかと。 PSoCも魅力的だけど入手性と価格がどうかなと。

**Comment by totegamma** [comment]
PR出しました #8
